# Generated by Django 4.1.7 on 2023-06-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_modal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_table',
            name='budget_type',
            field=models.CharField(choices=[('inc', '+'), ('exp', '-')], max_length=50),
        ),
    ]
