# Generated by Django 4.1.7 on 2023-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_modal', '0003_alter_budget_table_expense_alter_budget_table_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_table',
            name='expense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget_table',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
